# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96f8863f8ba817e13692bddc7bc9cf3d285f70b8d14d141da8ece70a9c72b7fe72bf5b22caca3c20c02423d882dd038075a532986ffaec62ec3fe460058869b1

test:
  secret_key_base: 180e62563611828d0fd1e2bb785e59bb593c14c7bd6571d2d113937f77e3819fc9c15c2b1de9c7d4c70aa31eec1e715e9687814c552f9311ab96490c667a9c63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
